mode: debug
media_root: media
media_url: /media
base_url: /
deploy_root: .site

template: hyde.ext.templates.jinja.Jinja2Template

plugins:
    - extensions.text.IndexingPlugin
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.meta.AutoExtendPlugin
    - hyde.ext.plugins.meta.TaggerPlugin
    - hyde.ext.plugins.text.SyntextPlugin


jinja2:
    filters:
        regex_replace: extensions.text.regex_replace
        regex_replace_fn: extensions.text.regex_replace_fn

markdown:
    extensions:
        - fenced_code
        - def_list
        - tables
        - headerid
        - codehilite
        - abbr
        - attr_list
        - admonition
        - toc
#        - pymdownx.smartsymbols
        - pymdownx.tasklist

context:
    data:
        author:
            name: Rob Sanderson
        project:
            name: Museum Linked Open Data
            url: "https://linked.art/"
            install: "https://github.com/linked-art/linked.art"
        menu:
          - title: Home
            url: index.html
          - title: LOUD
            url: loud/index.html
          - title: About
            url: about/index.html
          - title: Community
            url: community/index.html
          - title: Model
            url: model/index.html
          - title: Services
            url: api/index.html
          - title: Recipes
            url: cookbook/index.html
          - title: Software
            url: software/index.html

var:
    scheme: https
    hostname: linked.art
    exampleDir: example
    version: 1

###  Unnecessary, netlify CI deploy now set up
# publisher:
#     github:
#         type: hyde.ext.publishers.dvcs.Git
#         path: ../museum-lod-pages
#         url: https://github.com/azaroth42/museum-lod.git
#         branch: gh-pages

meta:
    # 'nodemeta' will tell Hyde what file to look for inside a folder from
    # which to apply meta data to all files (resources) inside it. This is
    # a great way of simply adding or modifying properties of a very large
    # number of files.
    nodemeta: meta.yaml
    ga_tracking_code: XX-XXXXXXXX-X
