mode: development
media_root: media
media_url: /media
base_url: /
deploy_root: ../museum-lod-pages

template: hyde.ext.templates.jinja.Jinja2Template

plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.meta.AutoExtendPlugin
    - hyde.ext.plugins.meta.TaggerPlugin
    - hyde.ext.plugins.text.SyntextPlugin

jinja2:
    filters:
        regex_replace: extensions.text.regex_replace

markdown:
    extensions:
        - fenced_code
        - def_list
        - tables
        - headerid
        - codehilite
        - abbr
        - attr_list
        - admonition
        - toc
        - pymdownx.githubemoji
        - pymdownx.headeranchor
        - pymdownx.smartsymbols
        - pymdownx.tasklist

context:
    data:
        author:
            name: Rob Sanderson
        project:
            name: Museum Linked Open Data
            url: "https://azaroth42.github.io/museum-lod/"
            install: "https://github.com/azaroth42/museum-lod"
        menu:
          - title: Home
            url: index.html
          - title: Introduction
            url: intro/index.html
          - title: Model
            url: model/index.html
          - title: Interactions
            url: api/index.html

var:
    scheme: https
    hostname: lod.shared-canvas.org
    exampleDir: example
    version: 1

publisher:
    github:
        type: hyde.ext.publishers.dvcs.Git
        path: ../museum-lod-pages
        url: https://github.com/azaroth42/museum-lod.git
        branch: gh-pages

### Advanced part ###

# This defines meta data on the whole site.
meta:
    # 'nodemeta' will tell Hyde what file to look for inside a folder from
    # which to apply meta data to all files (resources) inside it. This is
    # a great way of simply adding or modifying properties of a very large
    # number of files.
    nodemeta: meta.yaml
    ga_tracking_code: XX-XXXXXXXX-X

