mode: development
media_root: media
media_url: /media
base_url: /
# If your site is nested inside of a bigger one, you can use media_url and
# base_url to properly generate links on your site. For example, if your URL
# will be some.domain.com/starter/, use:
#   media_url: /starter/media
#   base_url: /starter/
template: hyde.ext.templates.jinja.Jinja2Template
plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.meta.AutoExtendPlugin
    - hyde.ext.plugins.meta.TaggerPlugin
    - hyde.ext.plugins.text.SyntextPlugin
markdown:
    extensions:
        - fenced_code
        - def_list
        - tables
        - headerid
        - codehilite
        - abbr
        - attr_list
        - admonition
        - toc
        - pymdownx.githubemoji
        - pymdownx.headeranchor
        - pymdownx.smartsymbols
        - pymdownx.tasklist
context:
    data:
        author:
            name: Rob Sanderson
            url: "http://..."
        project:
            name: Museum Linked Open Data
            url: "http://.../"
            install: "https://github.com/azaroth42/museum-lod"
        menu:
          - title: Home
            url: index.html
          - title: Introduction
            url: intro/index.html
          - title: Model
            url: model/index.html
          - title: Interactions
            url: api/index.html

var:
    hostname: azaroth42.github.io
    version: 1
    example_hostname: example.museum

publisher:
    github:
        type: hyde.ext.publishers.dvcs.Git
        path: deploy
        url: https://github.com/azaroth42/temp-museum-lod.git
        branch: gh-pages

### Advanced part ###

# This defines meta data on the whole site.
meta:
    # 'nodemeta' will tell Hyde what file to look for inside a folder from
    # which to apply meta data to all files (resources) inside it. This is
    # a great way of simply adding or modifying properties of a very large
    # number of files.
    nodemeta: meta.yaml
    ga_tracking_code: XX-XXXXXXXX-X

