extends: base.j2
default_block: content
level: top

example:
    actor_active: person/22.json
    actor_biog: person/18.json
    actor_birthdeath: person/17.json
    actor_gender: person/21.json
    actor_identity: person/16.json
    actor_image: person/19.json
    actor_membership: person/23.json
    actor_name: person/14.json
    actor_name_parts: person/15.json
    actor_nationality: person/20.json
    actor_type: activity/46.json
    actor_ulan: person/24.json
    assert_naming: activity/58.json
    assert_style_of: activity/59.json
    auction_base: activity/31.json
    auction_catalog: info/1.json
    auction_lot: activity/33.json
    auction_lotset: object/17.json
    auction_prices: object/20.json
    auction_purchase: activity/36.json
    auction_purchase_price: activity/38.json
    base_parts_activity: activity/0.json
    base_parts_info: info/0.json
    base_parts_org: group/0.json
    base_parts_place: place/0.json
    base_parts_thing: object/1.json
    base_stmt: object/2.json
    base_type: object/0.json
    exh_activity: activity/48.json
    exh_custody: activity/50.json
    exh_image: activity/54.json
    exh_labels: activity/52.json
    exh_multi: activity/55.json
    exh_objects: activity/49.json
    objabout_depicts: object/33.json
    objabout_description: object/30.json
    objabout_related: object/31.json
    objabout_style: object/35.json
    objabout_subject: object/34.json
    objdig_homepage: object/45.json
    objdig_iiif_image: object/47.json
    objdig_iiif_manifest: object/48.json
    objdig_image: object/44.json
    objdig_page: object/46.json
    objid_legacy: object/24.json
    objid_linkcoll: object/25.json
    objid_title: object/27.json
    objid_title_alt: object/28.json
    objid_types: object/29.json
    objphys_dims: object/36.json
    objphys_dims_stmt: object/37.json
    objphys_materials: object/38.json
    objphys_materials_stmt: object/39.json
    objprov_location: object/51.json
    objprov_owner: object/50.json
    objprov_production: object/49.json
    objrights_credit: object/40.json
    objrights_nkc: object/43.json
    objrights_rights: object/42.json
    objrights_rights_stmt: object/41.json
    prov_event: activity/1.json
    provacq_acq: activity/11.json
    provacq_loss: activity/14.json
    provacq_purchase: activity/12.json
    provacq_theft: activity/15.json
    provacq_theft_sale: activity/16.json
    provcur_curate: activity/18.json
    provcur_inventory: activity/21.json
    provcur_lifetime: activity/23.json
    provprod_copy: activity/7.json
    provprod_create: activity/2.json
    provprod_dest: activity/10.json
    provprod_previous: activity/9.json
    provprod_roles: activity/4.json
    provprod_technique: activity/3.json
    provprod_workshop: activity/8.json
