extends: base.j2
default_block: content
level: top

example:
    actor_active: person/18.json
    actor_biog: person/14.json
    actor_birthdeath: person/13.json
    actor_gender: person/17.json
    actor_identity: person/12.json
    actor_image: person/15.json
    actor_membership: person/19.json
    actor_name: person/10.json
    actor_name_parts: person/11.json
    actor_nationality: person/16.json
    actor_type: activity/40.json
    actor_ulan: person/20.json
    auction_base: activity/25.json
    auction_catalog: info/1.json
    auction_lot: activity/27.json
    auction_lotset: object/12.json
    auction_prices: object/15.json
    auction_purchase: activity/30.json
    auction_purchase_price: activity/32.json
    base_parts_activity: activity/0.json
    base_parts_info: info/0.json
    base_parts_org: group/0.json
    base_parts_place: place/0.json
    base_parts_thing: object/1.json
    base_stmt: object/2.json
    base_type: object/0.json
    exh_activity: activity/42.json
    exh_custody: activity/44.json
    exh_image: activity/48.json
    exh_labels: activity/46.json
    exh_multi: activity/49.json
    exh_objects: activity/43.json
    objabout_depicts: object/26.json
    objabout_description: object/25.json
    objabout_style: object/28.json
    objabout_subject: object/27.json
    objdig_homepage: object/38.json
    objdig_iiif_image: object/40.json
    objdig_iiif_manifest: object/41.json
    objdig_image: object/37.json
    objdig_page: object/39.json
    objid_legacy: object/19.json
    objid_linkcoll: object/20.json
    objid_title: object/22.json
    objid_title_alt: object/23.json
    objid_types: object/24.json
    objphys_dims: object/29.json
    objphys_dims_stmt: object/30.json
    objphys_materials: object/31.json
    objphys_materials_stmt: object/32.json
    objprov_location: object/44.json
    objprov_owner: object/43.json
    objprov_production: object/42.json
    objrights_credit: object/33.json
    objrights_nkc: object/36.json
    objrights_rights: object/35.json
    objrights_rights_stmt: object/34.json
    prov_acq: activity/4.json
    prov_create: activity/2.json
    prov_create_technique: activity/3.json
    prov_curate: activity/12.json
    prov_dest: activity/11.json
    prov_event: activity/1.json
    prov_inventory: activity/15.json
    prov_lifetime: activity/17.json
    prov_loss: activity/7.json
    prov_purchase: activity/5.json
    prov_theft: activity/8.json
    prov_theft_sale: activity/9.json
